# Generated by Django 5.0.4 on 2024-05-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexplainer',
            name='_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
